# Generated by Django 6.0.3 on 2026-03-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('baoCaoId', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiPhi',
            fields=[
                ('maChiPhi', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('moTa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('loaiId', models.AutoField(primary_key=True, serialize=False)),
                ('tenLoai', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThuNhap',
            fields=[
                ('incomeId', models.AutoField(primary_key=True, serialize=False)),
                ('soLuong', models.FloatField()),
                ('date', models.DateField()),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('thoiGianTao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='chiphi',
            name='loai',
            field=models.ForeignKey(db_column='loaiId', on_delete=django.db.models.deletion.CASCADE, to='expenses.loai'),
        ),
        migrations.AddField(
            model_name='thunhap',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='expenses.user'),
        ),
        migrations.AddField(
            model_name='chiphi',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='expenses.user'),
        ),
        migrations.AddField(
            model_name='baocao',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='expenses.user'),
        ),
    ]
