# Generated by Django 6.0.3 on 2026-03-31 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_baocao_chiphi_loai_thunhap_user_delete_testmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thunhap',
            old_name='mota',
            new_name='moTa',
        ),
        migrations.RemoveField(
            model_name='thunhap',
            name='soLuong',
        ),
        migrations.AddField(
            model_name='thunhap',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Số tiền'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thunhap',
            name='loai',
            field=models.ForeignKey(blank=True, db_column='loaiId', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.loai'),
        ),
        migrations.AlterField(
            model_name='loai',
            name='type',
            field=models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi phí')], max_length=50),
        ),
    ]
