# Generated by Django 5.1.1 on 2026-04-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_chiphi_primary_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiphi',
            name='amount',
            field=models.FloatField(verbose_name='Số tiền chi'),
        ),
        migrations.AlterField(
            model_name='chiphi',
            name='loai',
            field=models.ForeignKey(blank=True, db_column='loaiId', null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.loai'),
        ),
        migrations.AlterField(
            model_name='chiphi',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='chi_phis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thunhap',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='thu_nhaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
