# Generated by Django 5.1.1 on 2026-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_allow_null_loai_chiphi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loai',
            name='color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='loai',
            name='icon',
            field=models.CharField(default='plus', max_length=50),
        ),
    ]
