# Generated by Django 5.1.1 on 2026-04-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_loai_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiphi',
            name='loai',
            field=models.ForeignKey(blank=True, db_column='loaiId', null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.loai'),
        ),
        migrations.AlterField(
            model_name='thunhap',
            name='loai',
            field=models.ForeignKey(blank=True, db_column='loaiId', null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.loai'),
        ),
    ]
