# Generated by Django 6.0.3 on 2026-04-22 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_profile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thunhap',
            index=models.Index(fields=['user', 'date'], name='expenses_th_userId_6edcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='thunhap',
            index=models.Index(fields=['loai'], name='expenses_th_loaiId_04c951_idx'),
        ),
        migrations.AddIndex(
            model_name='thunhap',
            index=models.Index(fields=['amount'], name='expenses_th_amount_6e7c3c_idx'),
        ),
    ]
