# Generated by Django 6.0.3 on 2026-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('custom', 'Custom')], default='equal', max_length=20),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
