# Generated by Django 6.0.3 on 2026-04-22 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_fund', '0003_fundinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['fund', 'date'], name='shared_fund_fund_id_3d2de9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount'], name='shared_fund_amount_30ae17_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by'], name='shared_fund_created_e23ea2_idx'),
        ),
    ]
